// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6JWe7lnYRbCK2TxzfV-iacGTkosYWN9M',
    appId: '1:638917452083:web:ba29acc8f9d6fb9a369e46',
    messagingSenderId: '638917452083',
    projectId: 'sohleecelest-2301028c-pc09',
    authDomain: 'sohleecelest-2301028c-pc09.firebaseapp.com',
    storageBucket: 'sohleecelest-2301028c-pc09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBumYLnyY5HuIrQan5IV-7Mh58JkRySlH4',
    appId: '1:638917452083:android:ffe6596fbac34d32369e46',
    messagingSenderId: '638917452083',
    projectId: 'sohleecelest-2301028c-pc09',
    storageBucket: 'sohleecelest-2301028c-pc09.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6JWe7lnYRbCK2TxzfV-iacGTkosYWN9M',
    appId: '1:638917452083:web:091d7e89218bcb8a369e46',
    messagingSenderId: '638917452083',
    projectId: 'sohleecelest-2301028c-pc09',
    authDomain: 'sohleecelest-2301028c-pc09.firebaseapp.com',
    storageBucket: 'sohleecelest-2301028c-pc09.appspot.com',
  );
}
